grid: grid30

estimation:
  N_SA: 453
  eta: 0.05
  plot_exec_time: False

solution:
  T: 3
  eta: 0.05
  N0: 3 
  k: 160
  N_step: 30
  L: 50
  make_reduction: false
  dro: null
    
data:
  sigma_scale: 1


paths:
  saves_dir: /app/saves
  dro_results: /app/saves/dd-dro
