grid: grid145

estimation:
  N_SA: 633
  eta: 0.01
  plot_exec_time: False

solution:
  T: 3
  eta: 0.01
  N0: 3 
  k: 10
  N_step: 4
  L: 10
  make_reduction: false
  dro: null
    



paths:
  saves_dir: /app/saves
  dro_results: /app/saves/dd-dro
