grid: grid14

estimation:
  N_SA: 138
  eta: 0.05
  plot_exec_time: True

solution:
  T: 3
  eta: 0.05
  N0: 3 #N_SA = list(range(1, k))[::N_step][-1]
  k: 60
  N_step: 15
  L: 50
  make_reduction: false
  dro: null
    
data:
  sigma_scale: 1


paths:
  saves_dir: /app/saves
  dro_results: /app/saves/dd-dro
