grid: grid300

estimation:
  N_SA: 18
  eta: 0.001
  plot_exec_time: False

solution:
  T: 3
  eta: 0.001
  N0: 3 
  k: 10
  N_step: 5
  L: 10
  make_reduction: false
  dro: null
    
data:
  sigma_scale: 1


paths:
  saves_dir: /app/saves
  dro_results: /app/saves/dd-dro
