grid: grid14

estimation:
  N_SA: 363
  eta: 0.01
  plot_exec_time: True

solution:
  T: 3
  eta: 0.01
  N0: 3 #N_SA = list(range(1, k))[::N_step][-1]
  k: 150
  N_step: 30
  L: 50
  make_reduction: true
  dro: null
    
data:
  sigma_scale: 1


paths:
  saves_dir: /app/saves/reduction
  dro_results: /app/saves/reduction/dd-dro/
